### PR TITLE
Add env variable

### PR DESCRIPTION
**Pull request by prettyokay-software**
Indicate the process was started by SuperLTI using an env variable named SuperLTI since the embedded script can't rely on the command line containing SuperLTI.exe anymore

### CODE REVIEW

**Comment by krisdb2009** [comment]
That's a good idea!

**Comment by krisdb2009** [comment]
Just for future references, this kind of stuff can be done in this script that is run before the install script.

https://github.com/belowaverage-org/SuperLTI/blob/master/SuperLTI/Resources/SuperLTI.ps1

**Comment by prettyokay-software** [comment]
Yep... Putting it in that script would have made a lot more sense 🤦‍♂️
________________________________

**Comment by krisdb2009** [comment]
😂 No biggie.

**Pull request merged**
